# Generated by Django 4.2.7 on 2025-12-15 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('summary', models.TextField()),
                ('image_url', models.URLField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=200)),
                ('published_date', models.DateField()),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('rank', models.IntegerField()),
                ('points', models.IntegerField()),
                ('gender', models.CharField(choices=[('ATP', 'ATP'), ('WTA', 'WTA')], max_length=3)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('coach', models.CharField(blank=True, max_length=200, null=True)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('tournaments_played', models.IntegerField(default=0)),
                ('image_url', models.URLField(max_length=500)),
                ('biography', models.TextField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, help_text='Height in cm', null=True)),
                ('weight', models.IntegerField(blank=True, help_text='Weight in kg', null=True)),
                ('plays', models.CharField(blank=True, help_text='Playing style', max_length=100, null=True)),
                ('turned_pro', models.IntegerField(blank=True, null=True)),
                ('career_prize_money', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ace_count', models.IntegerField(default=0)),
                ('double_faults', models.IntegerField(default=0)),
                ('break_points_saved', models.FloatField(default=0.0)),
                ('first_serve_percentage', models.FloatField(default=0.0)),
                ('hard_wins', models.IntegerField(default=0)),
                ('clay_wins', models.IntegerField(default=0)),
                ('grass_wins', models.IntegerField(default=0)),
                ('best_ranking', models.IntegerField(blank=True, null=True)),
                ('weeks_at_no1', models.IntegerField(default=0)),
                ('grand_slam_titles', models.IntegerField(default=0)),
                ('masters_titles', models.IntegerField(default=0)),
                ('atp_finals_titles', models.IntegerField(default=0)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('weaknesses', models.TextField(blank=True, null=True)),
                ('favorite_tournament', models.CharField(blank=True, max_length=200, null=True)),
                ('career_highlights', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('surface', models.CharField(choices=[('Hard', 'Hard'), ('Clay', 'Clay'), ('Grass', 'Grass'), ('Carpet', 'Carpet')], max_length=100)),
                ('prize_money', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('Grand Slam', 'Grand Slam'), ('ATP Finals', 'ATP Finals'), ('WTA Finals', 'WTA Finals'), ('Masters 1000', 'Masters 1000'), ('WTA 1000', 'WTA 1000'), ('ATP 500', 'ATP 500'), ('WTA 500', 'WTA 500'), ('ATP 250', 'ATP 250'), ('WTA 250', 'WTA 250')], max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('total_matches', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=10)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('favorite_players', models.ManyToManyField(blank=True, to='api.player')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, help_text='Final position in tournament', null=True)),
                ('prize_money_earned', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('matches_won', models.IntegerField(default=0)),
                ('matches_lost', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tournament')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('tournament', 'player')},
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(related_name='tournaments_participated', through='api.TournamentParticipation', to='api.player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_wins', to='api.player'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('round', models.CharField(choices=[('Final', 'Final'), ('Semifinal', 'Semifinal'), ('Quarterfinal', 'Quarterfinal'), ('Round of 16', 'Round of 16'), ('Round of 32', 'Round of 32'), ('Round of 64', 'Round of 64'), ('Round of 128', 'Round of 128'), ('Qualifying', 'Qualifying')], max_length=50)),
                ('surface', models.CharField(choices=[('Hard', 'Hard'), ('Clay', 'Clay'), ('Grass', 'Grass')], max_length=50)),
                ('sets', models.JSONField(default=list, help_text='List of set scores, e.g., [6-4, 7-5]')),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('total_points', models.IntegerField(default=0)),
                ('player1_aces', models.IntegerField(default=0)),
                ('player2_aces', models.IntegerField(default=0)),
                ('player1_double_faults', models.IntegerField(default=0)),
                ('player2_double_faults', models.IntegerField(default=0)),
                ('player1_break_points', models.IntegerField(default=0)),
                ('player2_break_points', models.IntegerField(default=0)),
                ('player1_first_serve_percentage', models.FloatField(default=0.0)),
                ('player2_first_serve_percentage', models.FloatField(default=0.0)),
                ('highlights', models.TextField(blank=True, null=True)),
                ('attendance', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to='api.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to='api.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.tournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_won', to='api.player')),
            ],
            options={
                'ordering': ['-date', 'tournament'],
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.IntegerField()),
                ('matches_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('hard_wins', models.IntegerField(default=0)),
                ('hard_losses', models.IntegerField(default=0)),
                ('clay_wins', models.IntegerField(default=0)),
                ('clay_losses', models.IntegerField(default=0)),
                ('grass_wins', models.IntegerField(default=0)),
                ('grass_losses', models.IntegerField(default=0)),
                ('tournaments_played', models.IntegerField(default=0)),
                ('titles_won', models.IntegerField(default=0)),
                ('finals_reached', models.IntegerField(default=0)),
                ('semifinals_reached', models.IntegerField(default=0)),
                ('quarterfinals_reached', models.IntegerField(default=0)),
                ('prize_money', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('points_earned', models.IntegerField(default=0)),
                ('career_high_ranking', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='api.player')),
            ],
            options={
                'ordering': ['-season_year'],
                'unique_together': {('player', 'season_year')},
            },
        ),
        migrations.CreateModel(
            name='HeadToHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_matches', models.IntegerField(default=0)),
                ('player1_wins', models.IntegerField(default=0)),
                ('player2_wins', models.IntegerField(default=0)),
                ('last_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.match')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_to_head_as_player1', to='api.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_to_head_as_player2', to='api.player')),
            ],
            options={
                'verbose_name_plural': 'Head to Head stats',
                'unique_together': {('player1', 'player2')},
            },
        ),
    ]
